esphome:
  name: aaa
  friendly_name: aaa

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

external_components:
  - source:
      type: git
      url: https://github.com/pipacsba/esphome_hunter_wifi.git

hunter_wifi:
  pin: 16
  valves:
    - id: "lawn_sprinkler_valve_sw0"
      zone: 1
      max_duation: 6
    - id: "lawn_sprinkler_valve_sw1"
      zone: 2
      max_duration: 10


